name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        make model_test
        make api_test
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy carlos-sierra-challenge --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge_mle --region us-east4 --platform managed
