name: 'Continuous Integration'

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black

    - name: Check with Pylint
      run: |
        pylint **/*.py

    - name: Format with Black
      run: |
        black --check .

    - name: Run tests
      run: |
        make model_test
        make api_test
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/auth@v0.4.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

     - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge_mle .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge_mle